### ISSUE TITLE
I follow the steps, and when I click on "start", nothing happens.

### ISSUE THREAD

**Issue by mateusfbsoares** [kawhicurry/WebSoccerMonitor-plain#1]
Is this expected behaviour?

**Comment by kawhicurry** [comment]
Of course not, sorry, I should update my README earlier.

The normal behaviour should look like this:
1. start rcssserver with json protocol
2. start python3 scripts. Nothing output with script, but rcssserver indicates a monitor is connected.
3. start index.html. Players is put in correct position.

I got why `start` button didn't work. I havn't finished it yet. You can start another monitor and start the game now. You will see player moving in the field correctly.

Anyway, I just finished the part of `show the game`. I will avoid keeping useless button here next time.

**Comment by mateusfbsoares** [comment]
Ok! No problem. Thanks for explaining
